name: Create a Pull Request in solana-com on PR merge

on:
  push:
    branches:
      - master

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ecosystem...
        uses: actions/checkout@v2
        with:
          path: ecosystem

      - name: Checkout solana-com...
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SOLANA_PAT }}
          repository: timhagn/solana-th
          path: solana-th

      - name: Add changes to solana-com
        run: |
          ls -la
          /usr/bin/git --version
          cp $GITHUB_WORKSPACE/ecosystem/partners/* $GITHUB_WORKSPACE/solana-th/src/partners/
          cp $GITHUB_WORKSPACE/ecosystem/img/* $GITHUB_WORKSPACE/solana-th/static/img/

      - name: Create PR in solana-com...
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.SOLANA_PAT }}
          base: master
          path: $GITHUB_WORKSPACE/solana-th
